Building an End-to-End Data Engineering Pipeline for E-Commerce Order Analytics

Step 1: EXTRACT - Baca Data Mentah

In [24]:
from pathlib import Path
import pandas as pd
import numpy as np  
import ast
# Import semua data raw 
data = pd.read_csv("../data/raw/raw_customers.csv")

data.head(20)

,customer_id,customer_email,customer_name,phone_number,join_date,kota,gender,segment
0,CUST-0001,customer1@email.com,Farid Saputra,8.334233e+10,2023-10-04 01:01:00,Surabaya,P,premium
1,CUST-0002,customer2@email.com,Jefri Saputra,8.831408e+08,2023-07-08,solo,Laki-laki,Regular
2,CUST-0003,customer3@email.com,Omar Firmansyah,8.244566e+10,2023-01-22 03:22:00,semarang,Laki-laki,Regular
3,CUST-0004,customer4@email.com,YOGA FADILLAH,8.205764e+08,"Sep 14, 2023",YOGYAKARTA,M,Premium
4,CUST-0005,customer5@email.com,Hendra Wijaya,8.207095e+08,04/04/2023,malang,Perempuan,New
5,CUST-0006,customer6@email.com,Rafi Wibowo,8.378329e+10,2023-10-13,Denpasar,P,regular
6,CUST-0007,customer7@email.com,Reza Rahman,8.847525e+08,"Mar 28, 2023",JAKARTA,NaN,Regular
7,CUST-0008,customer8@email.com,Kevin Nugroho,8.235153e+10,2023-11-06 12:56:00,Solo,Laki-laki,Premium
8,CUST-0009,customer9@email.com,Bagas Fadillah,8.675034e+08,2023-09-30 11:14:00,bandung,Perempuan,Regular
9,CUST-0010,customer10@email.com,fajar pratama,8.821761e+10,07/10/2023,malang,M,regular
10,CUST-0011,customer11@email.com,Eko Rahman,8.115410e+08,19/11/2023,DENPASAR,NaN,New
11,CUST-0012,customer12@email.com,Miftah Pratama,8.838597e+10,2023-08-19,Denpasar,NaN,New
12,CUST-0013,customer13@email.com,Ilham Maulana,8.427496e+10,08-09-2023,jakarta,Perempuan,Regular
13,CUST-0014,customer14@email.com,Farid Halim,8.512738e+08,07/04/2023,medan,L,Regular
14,CUST-0015,customer15@email.com,Bayu Kusuma,6.282350e+11,2023-02-09 17:10:00,makassar,NaN,premium
15,CUST-0016,customer16@email.com,Taufan Hidayat,8.369980e+08,"Dec 06, 2023",MALANG,F,VIP
16,CUST-0017,customer17@email.com,Wisnu Maulana,8.556996e+10,16-12-2022,Denpasar,M,Premium
17,CUST-0018,customer18@email.com,Andi Kusuma,NaN,09/01/2023,Semarang,M,Premium
18,CUST-0019,customer19@email.com,fikri alamsyah,8.303011e+10,2023-08-05 06:06:00,surabaya,Perempuan,VIP
19,CUST-0020,customer20@email.com,Taufan Firmansyah,8.977053e+08,01/11/2023,Jakarta,F,VIP

In [25]:
# Inspeksi awal
print(f"Jumlah baris: {len(data)}")
print(f"Kolom: {list(data.columns)}")
data.info()

Jumlah baris: 55
Kolom: ['customer_id', 'customer_email', 'customer_name', 'phone_number', 'join_date', 'kota', 'gender', 'segment']
<class 'pandas.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     54 non-null     str
 1   customer_email  55 non-null     str
 2   customer_name   54 non-null     str
 3   phone_number    50 non-null     float64
 4   join_date       55 non-null     str
 5   kota            55 non-null     str
 6   gender          44 non-null     str
 7   segment         54 non-null     str
dtypes: float64(1), str(7)
memory usage: 3.6 KB

In [26]:
print("\nDuplikasi")
print(f"{data.duplicated().sum()}")

Duplikasi
0

In [27]:
print("\nMissing values:")
print(data.isnull().sum())

Missing values:
customer_id        1
customer_email     0
customer_name      1
phone_number       5
join_date          0
kota               0
gender            11
segment            1
dtype: int64

In [28]:
data.nunique()

customer_id       51
customer_email    52
customer_name     50
phone_number      47
join_date         51
kota              25
gender             6
segment            6
dtype: int64

In [29]:
# Nilai Negatif
phone_negatif = data[data['phone_number']< 0]
print(phone_negatif)

Empty DataFrame
Columns: [customer_id, customer_email, customer_name, phone_number, join_date, kota, gender, segment]
Index: []

Step 2: TRANSFORM - Bersihkan Data

In [30]:
# Menentukan kolom yang akan diperiksa
kolom = [
    'customer_id',
    'customer_email',
    'customer_name',
    'phone_number',
    'join_date',
    'kota',
    'gender',
    'segment'
]

# Menampilkan semua baris yang memiliki minimal satu missing value
missing_data = data[data[kolom].isna().any(axis=1)]

display(missing_data)

,customer_id,customer_email,customer_name,phone_number,join_date,kota,gender,segment
6,CUST-0007,customer7@email.com,Reza Rahman,8.847525e+08,"Mar 28, 2023",JAKARTA,NaN,Regular
10,CUST-0011,customer11@email.com,Eko Rahman,8.115410e+08,19/11/2023,DENPASAR,NaN,New
11,CUST-0012,customer12@email.com,Miftah Pratama,8.838597e+10,2023-08-19,Denpasar,NaN,New
14,CUST-0015,customer15@email.com,Bayu Kusuma,6.282350e+11,2023-02-09 17:10:00,makassar,NaN,premium
17,CUST-0018,customer18@email.com,Andi Kusuma,NaN,09/01/2023,Semarang,M,Premium
22,CUST-0023,customer23@email.com,Arif Hidayat,8.320972e+08,18/06/2023,malang,NaN,regular
24,CUST-0025,customer25@email.com,Fikar Wijaya,NaN,2023-10-01 16:58:00,Denpasar,L,premium
25,CUST-0026,customer26@email.com,JOKO WIBOWO,NaN,2023-04-05 03:56:00,Yogyakarta,M,premium
31,CUST-0032,customer32@email.com,Yudi Rahman,8.121818e+10,2023-10-26 08:02:00,jakarta,NaN,Premium
34,CUST-0035,customer35@email.com,Nizar Hidayat,8.574699e+08,2023-09-18 19:47:00,Bandung,NaN,Premium
35,CUST-0036,customer36@email.com,NaN,8.545852e+08,2023-07-04,Makassar,NaN,New
37,CUST-0038,customer38@email.com,Tono Nugroho,8.474635e+08,03-06-2023,MALANG,NaN,premium
47,CUST-0048,customer48@email.com,Bagas Pratama,8.996008e+08,03-09-2023,YOGYAKARTA,NaN,regular
49,CUST-0050,customer50@email.com,Bayu Setiawan,NaN,2023-05-01,MAKASSAR,Laki-laki,premium
51,CUST-0015,customer15@email.com,Bayu Kusuma,6.282350e+11,2023-02-09 17:10:00,MALANG,NaN,premium
54,NaN,customer51@email.com,fikri hakim,NaN,2024-01-20,bandung,L,NaN

In [31]:
# Langsung menhhapus data yang NaN pada customers_id 
data = data.dropna(subset=['customer_id'])

In [32]:
kolom = ['customer_name', 'kota', 'segment']

for col in kolom:
    data[col] = data[col].str.strip().str.title()

display(data[kolom].head(10))

     customer_name        kota  segment
0    Farid Saputra    Surabaya  Premium
1    Jefri Saputra        Solo  Regular
2  Omar Firmansyah    Semarang  Regular
3    Yoga Fadillah  Yogyakarta  Premium
4    Hendra Wijaya      Malang      New
5      Rafi Wibowo    Denpasar  Regular
6      Reza Rahman     Jakarta  Regular
7    Kevin Nugroho        Solo  Premium
8   Bagas Fadillah     Bandung  Regular
9    Fajar Pratama      Malang  Regular

In [33]:
# Menentukan kolom yang akan diperiksa
kolom = [
    'customer_id',
    'customer_email',
    'customer_name',
    'phone_number',
    'join_date',
    'kota',
    'gender',
    'segment'
]

# Menampilkan semua baris yang memiliki minimal satu missing value
missing_data = data[data[kolom].isna().any(axis=1)]

display(missing_data)

,customer_id,customer_email,customer_name,phone_number,join_date,kota,gender,segment
6,CUST-0007,customer7@email.com,Reza Rahman,8.847525e+08,"Mar 28, 2023",Jakarta,NaN,Regular
10,CUST-0011,customer11@email.com,Eko Rahman,8.115410e+08,19/11/2023,Denpasar,NaN,New
11,CUST-0012,customer12@email.com,Miftah Pratama,8.838597e+10,2023-08-19,Denpasar,NaN,New
14,CUST-0015,customer15@email.com,Bayu Kusuma,6.282350e+11,2023-02-09 17:10:00,Makassar,NaN,Premium
17,CUST-0018,customer18@email.com,Andi Kusuma,NaN,09/01/2023,Semarang,M,Premium
22,CUST-0023,customer23@email.com,Arif Hidayat,8.320972e+08,18/06/2023,Malang,NaN,Regular
24,CUST-0025,customer25@email.com,Fikar Wijaya,NaN,2023-10-01 16:58:00,Denpasar,L,Premium
25,CUST-0026,customer26@email.com,Joko Wibowo,NaN,2023-04-05 03:56:00,Yogyakarta,M,Premium
31,CUST-0032,customer32@email.com,Yudi Rahman,8.121818e+10,2023-10-26 08:02:00,Jakarta,NaN,Premium
34,CUST-0035,customer35@email.com,Nizar Hidayat,8.574699e+08,2023-09-18 19:47:00,Bandung,NaN,Premium
35,CUST-0036,customer36@email.com,NaN,8.545852e+08,2023-07-04,Makassar,NaN,New
37,CUST-0038,customer38@email.com,Tono Nugroho,8.474635e+08,03-06-2023,Malang,NaN,Premium
47,CUST-0048,customer48@email.com,Bagas Pratama,8.996008e+08,03-09-2023,Yogyakarta,NaN,Regular
49,CUST-0050,customer50@email.com,Bayu Setiawan,NaN,2023-05-01,Makassar,Laki-laki,Premium
51,CUST-0015,customer15@email.com,Bayu Kusuma,6.282350e+11,2023-02-09 17:10:00,Malang,NaN,Premium

In [34]:
# Mengisi missing value pada kolom customer_email dengan dummy123@email.com 
data['customer_email'] = data['customer_email'].fillna('dummy123@email.com')

In [35]:
# Mengganti missing value customer_name menjadi dummy dengan nama yang  berbeda setiap dokumen
import random

first_names = [
    "Budi", "Andi", "Siti", "Rina", "Dimas",
    "Fajar", "Nadia", "Putri", "Agus", "Indah"
]

last_names = [
    "Santoso", "Pratama", "Saputra", "Wijaya", "Hidayat",
    "Lestari", "Permata", "Kusuma", "Nugroho", "Rahman"
]

mask = data['customer_name'].isna()

data.loc[mask, 'customer_name'] = [
    f"{random.choice(first_names)} {random.choice(last_names)}"
    for _ in range(mask.sum())
]

display(data[['customer_name']])

        customer_name
0       Farid Saputra
1       Jefri Saputra
2     Omar Firmansyah
3       Yoga Fadillah
4       Hendra Wijaya
5         Rafi Wibowo
6         Reza Rahman
7       Kevin Nugroho
8      Bagas Fadillah
9       Fajar Pratama
10         Eko Rahman
11     Miftah Pratama
12      Ilham Maulana
13        Farid Halim
14        Bayu Kusuma
15     Taufan Hidayat
16      Wisnu Maulana
17        Andi Kusuma
18     Fikri Alamsyah
19  Taufan Firmansyah
20      Dedi Setiawan
21     Wisnu Fadillah
22       Arif Hidayat
23   Galih Firmansyah
24       Fikar Wijaya
25        Joko Wibowo
26         Rian Hakim
27     Kevin Setiawan
28      Hafiz Pratama
29     Wisnu Fadillah
30        Hadi Rahman
31        Yudi Rahman
32       Dimas Wibowo
33       Fikar Wijaya
34      Nizar Hidayat
35        Siti Rahman
36       Dedi Nugroho
37       Tono Nugroho
38     Miftah Saputra
39        Nizar Utomo
40     Taufan Saputra
41      Farid Gunawan
42        Reza Wibowo
43     Kevin Ramadhan
44       Kurnia Utomo
45      Rian Setiawan
46       Bayu Nugroho
47      Bagas Pratama
48     Kurnia Maulana
49      Bayu Setiawan
50        Rafi Wibowo
51        Bayu Kusuma
52      Fajar Pratama
53        Rudi Ananta

In [36]:
# Mengisi phone number pada kolom phone_number dan mengganti formatnya dengan standar +
# Mengisi missing value dengan nomor dummy unik
# Mengubah kolom phone_number menjadi string
data['phone_number'] = data['phone_number'].astype('string')
mask = data['phone_number'].isna()
data.loc[mask, 'phone_number'] = [
    f'081200000{i:03d}'
    for i in range(1, mask.sum() + 1)
]
display(data[['phone_number']])

      phone_number
0    83342331444.0
1      883140807.0
2    82445662585.0
3      820576383.0
4      820709497.0
5    83783290795.0
6      884752529.0
7    82351531223.0
8      867503414.0
9    88217611860.0
10     811540956.0
11   88385972235.0
12   84274958945.0
13     851273847.0
14  628235034324.0
15     836998038.0
16   85569956444.0
17    081200000001
18   83030106617.0
19     897705310.0
20  628250519597.0
21     882556484.0
22     832097220.0
23     884593961.0
24    081200000002
25    081200000003
26     885863473.0
27   88067372072.0
28   82139027119.0
29     897775215.0
30   83376077463.0
31   81218179599.0
32  628559225330.0
33  628259014493.0
34     857469942.0
35     854585178.0
36     839854548.0
37     847463522.0
38     833966966.0
39     825521714.0
40     836445607.0
41     853779528.0
42   85296710795.0
43     878608612.0
44     841523529.0
45     819774839.0
46     810744212.0
47     899600766.0
48     869849511.0
49    081200000004
50   83783290795.0
51  628235034324.0
52   88217611860.0
53     812345678.0

In [37]:
# Standarisasi format phone number +62
import re
def format_phone(phone):
    if pd.isna(phone):
        return phone
    # Hilangkan karakter selain angka
    phone = re.sub(r'\D', '', str(phone))
    # Mengatasi format scientific notation
    if 'e+' in str(phone).lower():
        phone = str(int(float(phone)))
    if phone.startswith('62'):
        phone = '+' + phone
    elif phone.startswith('0'):
        phone = '+62' + phone[1:]
    elif phone.startswith('8'):
        phone = '+62' + phone
    return phone
data['phone_number'] = data['phone_number'].apply(format_phone)
display(data[['phone_number']])

       phone_number
0   +62833423314440
1     +628831408070
2   +62824456625850
3     +628205763830
4     +628207094970
5   +62837832907950
6     +628847525290
7   +62823515312230
8     +628675034140
9   +62882176118600
10    +628115409560
11  +62883859722350
12  +62842749589450
13    +628512738470
14   +6282350343240
15    +628369980380
16  +62855699564440
17   +6281200000001
18  +62830301066170
19    +628977053100
20   +6282505195970
21    +628825564840
22    +628320972200
23    +628845939610
24   +6281200000002
25   +6281200000003
26    +628858634730
27  +62880673720720
28  +62821390271190
29    +628977752150
30  +62833760774630
31  +62812181795990
32   +6285592253300
33   +6282590144930
34    +628574699420
35    +628545851780
36    +628398545480
37    +628474635220
38    +628339669660
39    +628255217140
40    +628364456070
41    +628537795280
42  +62852967107950
43    +628786086120
44    +628415235290
45    +628197748390
46    +628107442120
47    +628996007660
48    +628698495110
49   +6281200000004
50  +62837832907950
51   +6282350343240
52  +62882176118600
53    +628123456780

In [38]:
# Mengubah format tanggal menjadi standar ISO 2024-06-27
# Mengubah berbagai format tanggal menjadi datetime
data['join_date'] = pd.to_datetime(
    data['join_date'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
)
data['join_date'] = data['join_date'].dt.strftime('%Y-%m-%d')
print(data['join_date'].isna().sum())
data.head()

0

,customer_id,customer_email,customer_name,phone_number,join_date,kota,gender,segment
0,CUST-0001,customer1@email.com,Farid Saputra,+62833423314440,2023-04-10,Surabaya,P,Premium
1,CUST-0002,customer2@email.com,Jefri Saputra,+628831408070,2023-08-07,Solo,Laki-laki,Regular
2,CUST-0003,customer3@email.com,Omar Firmansyah,+62824456625850,2023-01-22,Semarang,Laki-laki,Regular
3,CUST-0004,customer4@email.com,Yoga Fadillah,+628205763830,2023-09-14,Yogyakarta,M,Premium
4,CUST-0005,customer5@email.com,Hendra Wijaya,+628207094970,2023-04-04,Malang,Perempuan,New

In [39]:
# Menentukan kolom yang akan diperiksa
kolom = [
    'customer_id',
    'customer_email',
    'customer_name',
    'phone_number',
    'join_date',
    'kota',
    'gender',
    'segment'
]

# Menampilkan semua baris yang memiliki minimal satu missing value
missing_data = data[data[kolom].isna().any(axis=1)]

display(missing_data)

,customer_id,customer_email,customer_name,phone_number,join_date,kota,gender,segment
6,CUST-0007,customer7@email.com,Reza Rahman,+628847525290,2023-03-28,Jakarta,NaN,Regular
10,CUST-0011,customer11@email.com,Eko Rahman,+628115409560,2023-11-19,Denpasar,NaN,New
11,CUST-0012,customer12@email.com,Miftah Pratama,+62883859722350,2023-08-19,Denpasar,NaN,New
14,CUST-0015,customer15@email.com,Bayu Kusuma,+6282350343240,2023-09-02,Makassar,NaN,Premium
22,CUST-0023,customer23@email.com,Arif Hidayat,+628320972200,2023-06-18,Malang,NaN,Regular
31,CUST-0032,customer32@email.com,Yudi Rahman,+62812181795990,2023-10-26,Jakarta,NaN,Premium
34,CUST-0035,customer35@email.com,Nizar Hidayat,+628574699420,2023-09-18,Bandung,NaN,Premium
35,CUST-0036,customer36@email.com,Siti Rahman,+628545851780,2023-04-07,Makassar,NaN,New
37,CUST-0038,customer38@email.com,Tono Nugroho,+628474635220,2023-06-03,Malang,NaN,Premium
47,CUST-0048,customer48@email.com,Bagas Pratama,+628996007660,2023-09-03,Yogyakarta,NaN,Regular
51,CUST-0015,customer15@email.com,Bayu Kusuma,+6282350343240,2023-09-02,Malang,NaN,Premium

In [40]:
# Missing value pada kolom gender akan di isi secra random Laki-Laki dan Perempuan 
import random
# Mengisi missing value pada kolom gender secara acak
mask = data['gender'].isna()
data.loc[mask, 'gender'] = [
    random.choice(['Laki-Laki', 'Perempuan'])
    for _ in range(mask.sum())]
# Menampilkan hasil
display(data[['customer_name', 'gender']].head(10))

     customer_name     gender
0    Farid Saputra          P
1    Jefri Saputra  Laki-laki
2  Omar Firmansyah  Laki-laki
3    Yoga Fadillah          M
4    Hendra Wijaya  Perempuan
5      Rafi Wibowo          P
6      Reza Rahman  Laki-Laki
7    Kevin Nugroho  Laki-laki
8   Bagas Fadillah  Perempuan
9    Fajar Pratama          M

In [41]:
# Penulisan gender semua data Normalisasi menjadi Laki-Laki dan Perempuan 
# Menghapus spasi dan mengubah menjadi huruf kecil
data['gender'] = (data['gender'].astype(str).str.strip().str.lower())
# Mapping ke format standar
mapping_gender = {
    'l': 'Laki-Laki',
    'lk': 'Laki-Laki',
    'laki': 'Laki-Laki',
    'laki-laki': 'Laki-Laki',
    'laki laki': 'Laki-Laki',
    'pria': 'Laki-Laki',
    'male': 'Laki-Laki',
    'm': 'Laki-Laki',
    'p': 'Perempuan',
    'pr': 'Perempuan',
    'perempuan': 'Perempuan',
    'wanita': 'Perempuan',
    'female': 'Perempuan',
    'f': 'Perempuan'}
# Mengganti sesuai mapping
data['gender'] = data['gender'].replace(mapping_gender)
# Menampilkan hasil
display(data[['gender']].head(10))

      gender
0  Perempuan
1  Laki-Laki
2  Laki-Laki
3  Laki-Laki
4  Perempuan
5  Perempuan
6  Laki-Laki
7  Laki-Laki
8  Perempuan
9  Laki-Laki

In [42]:
# Menentukan kolom yang akan diperiksa
kolom = [
    'customer_id',
    'customer_email',
    'customer_name',
    'phone_number',
    'join_date',
    'kota',
    'gender',
    'segment'
]
# Menampilkan semua baris yang memiliki minimal satu missing value
missing_data = data[data[kolom].isna().any(axis=1)]

display(missing_data)

Empty DataFrame
Columns: [customer_id, customer_email, customer_name, phone_number, join_date, kota, gender, segment]
Index: []

In [43]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     54 non-null     str
 1   customer_email  54 non-null     str
 2   customer_name   54 non-null     str
 3   phone_number    54 non-null     str
 4   join_date       54 non-null     str
 5   kota            54 non-null     str
 6   gender          54 non-null     str
 7   segment         54 non-null     str
dtypes: str(8)
memory usage: 3.5 KB

In [44]:
data.head(10)

,customer_id,customer_email,customer_name,phone_number,join_date,kota,gender,segment
0,CUST-0001,customer1@email.com,Farid Saputra,+62833423314440,2023-04-10,Surabaya,Perempuan,Premium
1,CUST-0002,customer2@email.com,Jefri Saputra,+628831408070,2023-08-07,Solo,Laki-Laki,Regular
2,CUST-0003,customer3@email.com,Omar Firmansyah,+62824456625850,2023-01-22,Semarang,Laki-Laki,Regular
3,CUST-0004,customer4@email.com,Yoga Fadillah,+628205763830,2023-09-14,Yogyakarta,Laki-Laki,Premium
4,CUST-0005,customer5@email.com,Hendra Wijaya,+628207094970,2023-04-04,Malang,Perempuan,New
5,CUST-0006,customer6@email.com,Rafi Wibowo,+62837832907950,2023-10-13,Denpasar,Perempuan,Regular
6,CUST-0007,customer7@email.com,Reza Rahman,+628847525290,2023-03-28,Jakarta,Laki-Laki,Regular
7,CUST-0008,customer8@email.com,Kevin Nugroho,+62823515312230,2023-06-11,Solo,Laki-Laki,Premium
8,CUST-0009,customer9@email.com,Bagas Fadillah,+628675034140,2023-09-30,Bandung,Perempuan,Regular
9,CUST-0010,customer10@email.com,Fajar Pratama,+62882176118600,2023-10-07,Malang,Laki-Laki,Regular

In [45]:
print("\nMissing values:")
print(data.isnull().sum())

Missing values:
customer_id       0
customer_email    0
customer_name     0
phone_number      0
join_date         0
kota              0
gender            0
segment           0
dtype: int64

In [46]:
# Simpan ke CSV data setelah proses atau clean
data.to_csv(
    "../data/warehouse/customers_clean.csv",
    index=False,
    encoding="utf-8"
)
# Melihat kembali data yang disimpan
data = pd.read_csv("../data/warehouse/customers_clean.csv")
data.head()

,customer_id,customer_email,customer_name,phone_number,join_date,kota,gender,segment
0,CUST-0001,customer1@email.com,Farid Saputra,62833423314440,2023-04-10,Surabaya,Perempuan,Premium
1,CUST-0002,customer2@email.com,Jefri Saputra,628831408070,2023-08-07,Solo,Laki-Laki,Regular
2,CUST-0003,customer3@email.com,Omar Firmansyah,62824456625850,2023-01-22,Semarang,Laki-Laki,Regular
3,CUST-0004,customer4@email.com,Yoga Fadillah,628205763830,2023-09-14,Yogyakarta,Laki-Laki,Premium
4,CUST-0005,customer5@email.com,Hendra Wijaya,628207094970,2023-04-04,Malang,Perempuan,New