Building an End-to-End Data Engineering Pipeline for E-Commerce Order Analytics

Step 1: EXTRACT - Baca Data Mentah

In [43]:
from pathlib import Path
import pandas as pd
import numpy as np  
import ast
# Import semua data raw 
data = pd.read_csv("../data/raw/raw_order_promo.csv")

data.head(10)

    order_id    promo_code
0  ORD-10004      KAHFBARU
1  ORD-10049  GRATISONGKIR
2  ORD-10011      KAHFBARU
3  ORD-10050     WEEKEND15
4  ORD-10126      GAJIAN50
5  ORD-10092    parfumkahf
6  ORD-10042      gajian50
7  ORD-10120      KAHFBARU
8  ORD-10045     WEEKEND15
9  ORD-10082  GRATISONGKIR

In [44]:
# Inspeksi awal
print(f"Jumlah baris: {len(data)}")
print(f"Kolom: {list(data.columns)}")
data.info()

Jumlah baris: 30
Kolom: ['order_id', 'promo_code']
<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    30 non-null     str
 1   promo_code  30 non-null     str
dtypes: str(2)
memory usage: 612.0 bytes

In [45]:
print("\nDuplikasi")
print(f"{data.duplicated().sum()}")

Duplikasi
1

In [46]:
# Mencari data duplikasi
duplikat = data[data.duplicated(keep=False)]
print(duplikat)

     order_id promo_code
3   ORD-10050  WEEKEND15
28  ORD-10050  WEEKEND15

In [47]:
print("\nMissing values:")
print(data.isnull().sum())

Missing values:
order_id      0
promo_code    0
dtype: int64

Step 2: TRANSFORM - Bersihkan Data

In [48]:
# Menghapus data duplicate karena memang sama kode promonya
data = data.drop_duplicates()

In [49]:
# Mengubah kode promo menjadi hurup besar semua atau UPPER
# Mengubah promo_code menjadi huruf besar semua
data['promo_code'] = (data['promo_code'].astype(str).str.strip().str.upper())
# Menampilkan hasil
print(data[['promo_code']])

      promo_code
0       KAHFBARU
1   GRATISONGKIR
2       KAHFBARU
3      WEEKEND15
4       GAJIAN50
5     PARFUMKAHF
6       GAJIAN50
7       KAHFBARU
8      WEEKEND15
9   GRATISONGKIR
10      RAMADHAN
11         VIP20
12    FACECARE10
13    FACECARE10
14   CUCI GUDANG
15      GAJIAN50
16         VIP20
17  GRATISONGKIR
18      RAMADHAN
19  GRATISONGKIR
20         VIP20
21    PARFUMKAHF
22  GRATISONGKIR
23      GAJIAN50
24         VIP20
25      GAJIAN50
26     WEEKEND15
27   CUCI GUDANG
29   EXPIRED2023

In [50]:
data.info

<bound method DataFrame.info of      order_id    promo_code
0   ORD-10004      KAHFBARU
1   ORD-10049  GRATISONGKIR
2   ORD-10011      KAHFBARU
3   ORD-10050     WEEKEND15
4   ORD-10126      GAJIAN50
5   ORD-10092    PARFUMKAHF
6   ORD-10042      GAJIAN50
7   ORD-10120      KAHFBARU
8   ORD-10045     WEEKEND15
9   ORD-10082  GRATISONGKIR
10  ORD-10109      RAMADHAN
11  ORD-10093         VIP20
12  ORD-10005    FACECARE10
13  ORD-10124    FACECARE10
14  ORD-10035   CUCI GUDANG
15  ORD-10079      GAJIAN50
16  ORD-10032         VIP20
17  ORD-10122  GRATISONGKIR
18  ORD-10107      RAMADHAN
19  ORD-10083  GRATISONGKIR
20  ORD-10003         VIP20
21  ORD-10087    PARFUMKAHF
22  ORD-10038  GRATISONGKIR
23  ORD-10015      GAJIAN50
24  ORD-10044         VIP20
25  ORD-10062      GAJIAN50
26  ORD-10068     WEEKEND15
27  ORD-10089   CUCI GUDANG
29  ORD-10099   EXPIRED2023>

In [51]:
# Simpan ke CSV data setelah proses atau clean
data.to_csv(
    "../data/warehouse/order_promo_clean.csv",
    index=False,
    encoding="utf-8"
)
# Melihat kembali data yang disimpan
data = pd.read_csv("../data/warehouse/order_promo_clean.csv")
data.head(10)

    order_id    promo_code
0  ORD-10004      KAHFBARU
1  ORD-10049  GRATISONGKIR
2  ORD-10011      KAHFBARU
3  ORD-10050     WEEKEND15
4  ORD-10126      GAJIAN50
5  ORD-10092    PARFUMKAHF
6  ORD-10042      GAJIAN50
7  ORD-10120      KAHFBARU
8  ORD-10045     WEEKEND15
9  ORD-10082  GRATISONGKIR